name: Node CI

on:
  push:
    branches:
      - master
      - canary
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x

      - name: Fix Python distutils (required by node-gyp)
        run: python3 -m pip install setuptools --break-system-packages || python3 -m pip install setuptools

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
